### PR TITLE
More options for tf_item_teamflag

### PR DESCRIPTION
**Pull request by yourbadandimbest**
Changes for feature request https://github.com/AmperSoftware/TF-Source-2/issues/64

# Changes

- New `Tintable` briefcase skin.
- Can now set model and tint. For compatability with custom models you will need to set the briefcase skin manually.
- Can now change the trail particle.
- Intelligence now visible even when disabled.

https://user-images.githubusercontent.com/91832803/214718453-61710b5d-2f51-42f2-bdaa-f3a0de9cea2b.mp4

### CODE REVIEW

**Comment by TheBoxTrot** [comment]
Could be a bit annoying for people who just want red or blue does it still have skin options for those?

**Comment by yourbadandimbest** [comment]
Yes. It still has the red, blu and neutral skin but also a fourth new tintable skin.

**Comment by qualitykk** [comment]
So you now have to manually change the skin when you want to change the team?

**Comment by yourbadandimbest** [comment]
> So you now have to manually change the skin when you want to change the team?

Correct. This was done so that it won't forcefully set the skins for custom models. I can revert this change if requested.

**Comment by qualitykk** [comment]
> > So you now have to manually change the skin when you want to change the team?
> 
> Correct. This was done so that it won't forcefully set the skins for custom models. I can revert this change if requested.

You dont have to, i was just double checking if thats what you wanted, ill merge it in a second since thats the only issue I can see with this.

**Pull request merged**
