### PR TITLE
Close voice menu after repeated `voice_menu` ccmd

### PR DESCRIPTION
**Pull request by lotuspar**
Completes feature request #21
Not sure about the `Toggle` naming though.

# Changes

If you have a voice_menu bind then:
- pressing it with a different page open will switch back to the page used in the command
- pressing it with the same page open will close the voice menu

### CODE REVIEW

**Review by Retr0-01 — CHANGES_REQUESTED** [review]
There are some issues with this PR. Assuming the player has ZXC voice_menu bindings:
- The last menu (C) will not be closed if pressed twice.
- The UI panel footer gets broken, showing no texture.

image

Other than that LGTM.
TIP: You can check if the user has rebound their View key (C by default) and then decide whether or not to show the ``footer`` and ``hint`` divs of [VoiceMenu.html](https://github.com/AmperSoftware/TF-Source-2/blob/dev/code/UI/HUD/Voice/VoiceMenu.html)

**Comment by lotuspar** [comment]
>     * The last menu (C) will not be closed if pressed twice.
I don't seem to have that problem, maybe I'm missing something?

I'll do the footer / hint hiding soon though!

**Comment by Retr0-01** [comment]
Hey, @lotuspar 

Have you managed to resolve the changes required?

**Review by Retr0-01 — APPROVED** [review]
Alright we are all good now! 👍 
Also I did not encounter the first problem I reported again so it might have been something from my side. Probably messed up the console commands.

**Comment by Retr0-01** [comment]
Posting this here because it's your latest PR @lotuspar 

For future reference please follow the PR guidelines, and specifically the referencing/linking of any related issues to a PR. Whenever a PR will get merged, all referenced issues will be closed and marked as completed. Otherwise they won't and they might be forgotten/kept open until one of us realizes.

You can read this detailed article in case you don't know how to properly link issues to PRs.
[GitHub - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Pull request merged**
